# Generated by Django 3.1.7 on 2021-03-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_final',
            field=models.DateTimeField(null=True, verbose_name='Saída'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='telefone',
            field=models.CharField(max_length=16, verbose_name='Telefone'),
        ),
    ]
