# Generated by Django 3.1.7 on 2021-03-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210306_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone'),
        ),
    ]
