# Generated by Django 3.1.7 on 2021-03-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210306_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descricao',
            field=models.CharField(default=1, max_length=255, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
