# Generated by Django 3.1.7 on 2021-03-13 19:58

from django.db import migrations, models
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210306_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='foto',
        ),
        migrations.AddField(
            model_name='evento',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='imagem',
            field=stdimage.models.StdImageField(default=django.utils.timezone.now, upload_to='Eventos', verbose_name='Imagem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='evento',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Evento'),
        ),
    ]
